"""followers

Revision ID: 20efdfff676b
Revises: dae87fc6b366
Create Date: 2021-02-13 07:24:31.134714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20efdfff676b'
down_revision = 'dae87fc6b366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
